### ISSUE TITLE
バージョン付与の統一

### ISSUE THREAD

**Issue by windyakin** [windyakin/Honoka#12]
現在HonokaとそのForkテーマ間でバージョンの付与方式が三者三様であるので、エンドユーザにも理解しやすくするため統一したい。
### 現状

現状は以下の通り。どれも一応セマンティックバージョニングの規約は守れているがバラバラなのが現状。

| Bootstrap | Honoka | Umi | Nico |
| :-: | :-: | :-: | :-: |
| (3.3.5) | 3.3.5-d | (None) | 3.3.5-1.0.0 |
|  | (None) | (None) | 3.3.5-1.0.1 |
| 3.3.6 | 3.3.6 | 3.3.6-1 | 3.3.6-1.1.0 |
|  | 3.3.6-a | 3.3.6-2 | 3.3.6-1.1.1 |
|  | 3.3.6-b | 3.3.6-3 | 3.3.6-1.1.2 |
#### Honoka
- Bootstrapのバージョンアップ時の初版
  - Bootstrapのバージョン番号と同じ
- Honokaの修正
  -  `-` 区切りで `a`, `b`, `c`... と英字によるバージョンの増加
#### Umi
- Bootstrapのバージョンアップ時の初版
  - Bootstrapのバージョン番号の後ろに `-` 区切りで `1` から番号を振る
- Honokaの修正
  - `-` 以降の数字を増やす
#### Nico
- Bootstrapのバージョンアップ時の初版
  - Bootstrapのバージョン番号の後ろにさらに独自に振ったバージョン番号の`MINOR`番号を上げる
- Honokaの修正
  - 独自に振ったバージョン番号の`PATCH`番号を上げる(?)
- Nico独自の修正
  - 独自に振ったバージョン番号の`PATCH`番号を上げる
### 気にしておくべき事項
- Bowerでバージョン番号を指定しない時、最新版がインストールされるようにしたい
  - 現在のHonokaのバージョン付けであると初版の優先度が高く、以降のHonoka独自修正のバージョンは指定しないとインストールされない
- Forkテーマ独自の修正の際にどうするか
  - Honokaに影響を与えない独自の修正（色など）をする際のバージョンの付け方
- Forkが対応しない場合
  - Honokaの変更に付いて来れない状態でバージョン変更に抜けができた場合どうするか
### 参考

[セマンティック バージョニング 2.0.0](http://semver.org/lang/ja/)

**Comment by NKMR6194** [comment]
バージョン付与の統一することには概ね賛成です。

いくつかバージョニングについていくつか提案します。私としてはUmiのバージョニングと同類のもの、もしくは提案の１つ目が良いと思っています。

### Honoka familyのバージョニングは`PATCH`でする

`MAJOR`.`MINOR`は元となるBootstrapのバージョンを流用し、`PATCH`でHonoka familyの独自アップデートを管理する。

#### 例

時系列に沿ったアップデート内容 | Honoka | Umi | Nico
----- |:-----:|:-----:|:-----:
Bootstrap 4.0.0に対応 | 4.0.0 | 4.0.0 |  4.0.0
Umi固有のアップデートをした | - | 4.0.1 | -
Honoka固有のアップデートをした | 4.0.1 | 4.0.2 | (対応しない)
Bootstrap 4.0.1に対応した | 4.0.2 | 4.0.3 | 4.0.1
Bootstrap 4.1.0に対応した | 4.1.0 | 4.1.0 | 4.1.0

### Bootstrapのバージョニングに関係なく Honoka family のバージョニングする

Umi や Nicoは`MAJOR`.`MINOR`についてはHonokaと同じバージョンを採用し、個別のアップデートで`PATCH`を変更する。

### Nico likeなバージョニングをする

ただし、Bootstrapの対応バージョンを上げた場合には`1.0.0`に戻す

**Comment by NKMR6194** [comment]
### Bootswatchのバージョニング例

* Bootstrapのバージョンアップ時の初版
  * Bootstrapのバージョン番号と同じ
* Bootswatchの修正
  *  `+` 区切りで `1`, `2`, `3` と数字によるバージョンの増加


[Bootswatch releases](https://github.com/thomaspark/bootswatch/releases)

**Comment by kubosho** [comment]
結論から言うと、自分もHonoka familyのバージョニングはPATCHでするでいいのではと思います。

今のNicoのバージョニングはBootstrapのバージョンが上がった場合、独自に振ったバージョンが上がっていきます。
たとえば4.0.0に対応した場合は、おそらく`4.0.0-2.0.0`となります。
ただバージョンが2つ表記されて分かりにくいのと、独自のバージョニングになってしまっている以上、このバージョニングは捨てる必要があると考えました。

**Comment by windyakin** [comment]
バージョニング形式の個人の意見としてはUmiのバージョニング形式が一番要求を満たせているかなと感じていたのですが…。

今までBootstrapとバージョン表記の互換を維持してきたのは、やはり何をベースにしているのか開発者にも利用者にもひと目にわかりやすいのが一番だったからだと思います。

あとHonoka family間のバージョン互換については、現状は基本的にバグ等があった場合にはHonokaにPull Req→Forkにmergeという流れになっているということ。またHonokaのForkテーマが独自の変更を加えるのはかなりのレアケースだと思うので、Honokaのバージョン表記に合わせる感じが一番手っ取り早いのではないでしょうか。

| Bootstrap | Honoka | Umi | Nico | 備考 |
|:---------:|:-------:|:-------:|:-------:|--------------------------|
| 4.0.0 | 4.0.0-1 | 4.0.0-1 | 4.0.0-1 | Bootstrapの4.0.0対応初版 |
|  | 4.0.0-2 | 4.0.0-2 | (None) | Honokaの変更 |
|  | 4.0.0-3 | (None) | 4.0.0-3 | Honokaの変更 |
|  | 4.0.0-4 | 4.0.0-4 | 4.0.0-4 | Honokaの変更 |
| 4.0.1 | 4.0.1-1 | 4.0.1-1 | 4.0.1-1 | Bootstrapの4.0.1対応初版 |

**Comment by NKMR6194** [comment]
Umiのバージョニング形式をとるのは賛成です。

ただ、そのレアケースもどうにかしたいですね。今まではHonokaのアップデートに混ぜて済ませていましたが、Bootstrap 4系へのアップデートでまたforkテーマ固有のバグが発生しやすくなるのではないかと思っています。

**Comment by kubosho** [comment]
すいません書いてなかったですが、Umiのバージョニング形式でもいいと思います。
レアケースは起きたらその時考える…でもいい気がします。

**Comment by windyakin** [comment]
なんとなく嫌な予感がしたので、検証してみました。

Umiは今まで全てのリリースを``MAJOR``.``MINOR``.``PATCH``-``ORIG``形式のバージョニングにしており、例えばHonokaで Bootstrap v3.3.6 対応初版の ``v3.3.6`` についても ``v3.3.6-1`` でリリースしています。なので Bower を使ってバージョン指定なしでインストールすると、 ``v.3.3.6-1`` が優先的にインストールされるようになっています。これは求めている挙動です。

```
% bower install git@github.com:NKMR6194/Umi.git
bower not-cached    git@github.com:NKMR6194/Umi.git#*
bower resolve       git@github.com:NKMR6194/Umi.git#*
bower checkout      Umi#v3.3.6-1
bower resolved      git@github.com:NKMR6194/Umi.git#3.3.6-1
bower install       Umi#3.3.6-1
```

Nicoの場合はv3.3.5の初版は``v3.3.5``、以降semverフォーマットへの準拠などを経て、v3.3.6の初版を ``v3.3.6-1.1.0`` でリリースしています。この場合どうなるかというと、

```
% bower install git@github.com:kubosho/Nico.git
bower not-cached    git@github.com:kubosho/Nico.git#*
bower resolve       git@github.com:kubosho/Nico.git#*
bower checkout      Nico#v3.3.5
bower invalid-meta  Nico is missing "main" entry in bower.json
bower invalid-meta  Nico is missing "ignore" entry in bower.json
bower resolved      git@github.com:kubosho/Nico.git#3.3.5
bower install       Nico#3.3.5

Nico#3.3.5 bower_components/Nico
```

``v3.3.6-1.1.0`` は無視され、 ``v3.3.5`` が最新版としてインストールされるようです。

検証として以下のリポジトリを作ってみました。

https://github.com/windyakin/bower_test

tagの切り方については[Releasesのページ](https://github.com/windyakin/bower_test/releases)を見てもらえればわかりますが、途中までハイフン区切り無しでtagを切っていて、途中からハイフン区切りをつけた場合(Umi形式にした場合)、やはりハイフン区切りが無かった``v1.0.1``が最新版としてインストールされるようです。

```
% bower install git@github.com:windyakin/bower_test.git
bower not-cached    git@github.com:windyakin/bower_test.git#*
bower resolve       git@github.com:windyakin/bower_test.git#*
bower checkout      bower_test#v1.0.1
bower invalid-meta  bower_test is missing "main" entry in bower.json
bower invalid-meta  bower_test is missing "ignore" entry in bower.json
bower resolved      git@github.com:windyakin/bower_test.git#1.0.1
bower install       bower_test#1.0.1

bower_test#1.0.1 bower_components/bower_test
```

というわけで現状、HonokaとNicoがUmiのバージョニングに対応した場合Bowerで最新版をインストールするにはやはり今までどおり、バージョンを直接指定するしかなさそうという検証でした。

どうにかできれば一番ですが、どうしたらいいんでしょうね。

**Comment by NKMR6194** [comment]
Bowerでうまく使えるようにしたいということなら`PATH`案が良い気がしますがどうなんですか？

私的にはBowerを全く使っていないので、普段使ってる方の都合を優先したいと思ってます

**Comment by kubosho** [comment]
Bowerで上手く使えるようにするという点では、`PATCH`案がいい気がします。
ただ、これも元のBootstrapのバージョンがどれになるのか分かりにくいという欠点はあり難しいところですね…

**Comment by windyakin** [comment]
ひとまずPATCH案で 4.0.0 リリースから統一する方向で調整したいと思ってます

**Comment by windyakin** [comment]
4.0.0 になったし思い出していこうな
