### ISSUE TITLE
$body-bg と $table-bg-accent が同じなので既定のままだと `.table-striped` で奇数行と偶数行が同じに見えます

### ISSUE THREAD

**Issue by KatsuYuzu** [windyakin/Honoka#19]
`$body-bg` と `$table-bg-accent` が同じなので既定のままだと `.table-striped` で奇数行と偶数行が同じに見えます。
https://github.com/windyakin/Honoka/blob/master/scss/honoka/_variables.scss#L14

`$table-bg-hover` とも調整しないといけないので、具体的な修正後のデザインは想像できていないです。

**Comment by KatsuYuzu** [comment]
`$body-bg` を取り上げたのは `$table-bg` が `transparent` なためです。
修正対象は `$table-FOO` の方だと思います。

**Comment by windyakin** [comment]
次期リリース(v3.3.6-b or v3.3.7)にて修正リリース出します
