### ISSUE TITLE
input-group-btn の高さがそろわない

### ISSUE THREAD

**Issue by lobin-z0x50** [windyakin/Honoka#20]
現在構築中の Web サイトで、Honoka の採用を検討しています。
1点気になったので Issue をあげさせて頂きました。

`input-group-btn` を使ってテキストボックスにボタンを連結させた際に、テキストボックスとボタンの下枠の線がずれて見えるようです。
![honoka-input-group-btn-gap](https://cloud.githubusercontent.com/assets/11419109/15708105/9d41b86c-2837-11e6-8e7f-dbd5981f3c21.png)

本家 Bootstrap 3 では、ずれていませんでした。
Chrome で再現確認、ただし Edge ではキレイに表示されており、ズレはありませんでした。他のブラウザは試していません。
何か対応策はあるでしょうか？

**Comment by windyakin** [comment]
font-sizeを上げたことによる小数点の切り捨てなどによる影響の可能性とかが考えられます。

修正にはソースコードの対応と思われるので対応までお待ち下さい。

**Comment by windyakin** [comment]
結論から言うとコーディング側の問題でした。

詳細は 64d6b5b を見て頂くとわかると思いますが、`.form-group` に `.input-lg` と `.btn-lg` を併用するのではなく、 `.form-group` と一緒に `.form-group-lg` を指定することで解決できます。

**Comment by lobin-z0x50** [comment]
:+1:
試してみます

**Comment by lobin-z0x50** [comment]
@windyakin `.form-group-lg` や `.form-group-sm` をつけたくない場合（標準サイズにしたい場合）はどうしたらいいでしょうか。`.form-group` だけだと、やはりずれて見えるようです。

**Comment by windyakin** [comment]
やはり小数点の処理が Firefox、Google Chrome だとどうしても入るようです。 ちょっと修正には手間取りそうなのでひとまずReOpenしておきます。

**Comment by windyakin** [comment]
f86b0d2 にて修正しました。（詳しくはコミットメッセージをご覧ください）

[v.3.3.6-b](https://github.com/windyakin/Honoka/releases/tag/v3.3.6-b) にて修正したものをダウンロードできますのでどうぞ。
