### ISSUE TITLE
<p>タグ内の半角文字等が挿入された時に画面からはみ出る

### ISSUE THREAD

**Issue by potato4d** [windyakin/Honoka#25]
iPhoneでサイト閲覧中に確認。

pタグに`word-break:break-all;`を指定することで解消可能。
なんなら全体に指定してしまうぐらいでも良いかもしれません。

<img width="321" alt="2016-09-22 12 53 32" src="https://cloud.githubusercontent.com/assets/6993514/18736622/ad13f9b4-80c3-11e6-9a8b-d87b49dd2eab.png">

閲覧サイト：
http://homomaid.com/
(HonokaのForkであるRinが使われていたが、読み込み先CSSをHonokaに変更しても再現。)

**Comment by potato4d** [comment]
補足：
`<code />`内であればこの形式で問題ない箇所ではありますが、タダの<p>の中のテキストでも再現します。

<img width="337" alt="2016-09-22 12 56 31" src="https://cloud.githubusercontent.com/assets/6993514/18736654/0fecda38-80c4-11e6-9cf0-adedc8ffca2b.png">

**Comment by windyakin** [comment]
当事象に関する対策として、 `word-wrap: break-word;` (#26) はひとつの解決策として、いたって普遍的で、通常でも行われる対処ではあります。

しかしその一方で `word-wrap: break-word;` が与える影響は、「全ての禁則処理を行わない」というものであり、通常の英単語の長さであっても、折り返しが行われてしまいます。これはCSSフレームワークとしては全体に与える影響が大きいものであり、本家Bootstrapでも「Coreでその機能を提供する必要はない」という結論の[Issueが存在する](https://github.com/twbs/bootstrap/issues/3066)ため、本Issue及びこれに関連するPRはCloseとさせていただきます。

また [homomaid.com](https://homomaid.com/) の事象に関しては、個別に `word-wrap: break-word;` を指定し、対応していただければと思います。

**Comment by potato4d** [comment]
:ok-hand:

**Comment by potato4d** [comment]
@windyakin 
本家の方でもそういう流れあったんですねー。
失礼。ありがとうございましたー👌
