### ISSUE TITLE
How about upload Honoka to NPM

### ISSUE THREAD

**Issue by jerrywdlee** [windyakin/Honoka#32]
Honokaは現在、Bower上しかいないが、モーダンな開発者はBowerよりWebpackを用いるケースが多くなり、ソースコード一元化管理の視点では、NPMにアップすることは大変助かります。
よろしくお願いいたします。

**Comment by windyakin** [comment]
https://www.npmjs.com/package/bootstrap-honoka にて公開したのでCloseします
