### ISSUE TITLE
Please allow me to introduce myself.

### ISSUE THREAD

**Issue by Xyncgas** [windyakin/Honoka#76]
Hi hi, what are you doing~? in what ways can I contributed to this?
I just read a henti manga, and I found out that the artist twitter has a link to the [国立音ノ木坂学院サーバー](http://otonokizaka.school/) website which is built by the framework you made.
Sugoii
Kagouii
I want to play with you. I don't speak japanese though. but I want to write codes in your projects

**Comment by windyakin** [comment]
There are several ways for you to contribute to this project. For example, if you find a bug or a typo, you can send a patch to fix it.

The way to send patches is as you know it. Fork this repository and send a pull request with the commit of the fix.

Thank you for your cooperation!
